language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
env:
  - DJANGO_VERSION=1.8.18
  - DJANGO_VERSION=1.9.13
  - DJANGO_VERSION=1.10.7
# https://docs.djangoproject.com/en/stable/faq/install/#what-python-version-can-i-use-with-django
matrix:
  exclude:
    - env: DJANGO_VERSION=1.8.18
      python: 3.6
    - env: DJANGO_VERSION=1.9.13
      python: 3.6
    - env: DJANGO_VERSION=1.10.7
      python: 3.6
addons:
  apt_packages:
    - pandoc
before_install:
    - ./pypi_packager.sh
install:
  - pip install -q django==$DJANGO_VERSION
  - pip install -e .[test]
  - pip install -q coveralls
script:
  - coverage run --source=constrainedfilefield constrainedfilefield/tests/__main__.py
after_success:
  - coveralls
