language: python
python:
  - 2.7
  - 3.4
  - 3.5
env:
  - DJANGO_VERSION=1.8.17
  - DJANGO_VERSION=1.9.12
  - DJANGO_VERSION=1.10.0
  - DJANGO_VERSION=1.10.1
  - DJANGO_VERSION=1.10.2
  - DJANGO_VERSION=1.10.3
  - DJANGO_VERSION=1.10.4
  - DJANGO_VERSION=1.10.5
# https://docs.djangoproject.com/en/1.9/faq/install/#what-python-version-can-i-use-with-django

install:
  - pip install django
  - pip install -e .
  - pip install coveralls
script:
  - coverage run --source=constrainedfilefield constrainedfilefield/tests/__main__.py
after_success:
  - coveralls
