language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
env:
  - DJANGO_VERSION=1.8.18
  - DJANGO_VERSION=1.9.13
  - DJANGO_VERSION=1.10.7
# https://docs.djangoproject.com/en/1.9/faq/install/#what-python-version-can-i-use-with-django

install:
  - pip install django
  - pip install -e .
  - pip install coveralls
script:
  - coverage run --source=constrainedfilefield constrainedfilefield/tests/__main__.py
after_success:
  - coveralls
